# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: tfsec

on:
  push:
    branches: [ "prod", "staging", "dev" ]
  pull_request:
    branches: [ "prod" ]
  schedule:
    - cron: '45 13 * * 2'

jobs:
  tfsec:
    name: tfsec-check
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install-linux.sh | bash

      - name: Run tfsec and save SARIF
        run: |
          mkdir -p tfsec-results
          tfsec . --format sarif > tfsec-results/tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec-results/tfsec.sarif

